export const GAME_STOP = 'GAME_STOP'
export const GAME_END = 'GAME_END'
export const GAME_START = 'GAME_START'
export const ROUND_START = 'ROUND_START'
export const ROUND_COMPLETE = 'ROUND_COMPLETE'
export const BATTLE_NEXT_PHASE = 'BATTLE_NEXT_PHASE'

export const MESSAGES_EMPTY = 'MESSAGES_EMPTY'
export const MESSAGES_ADD = 'MESSAGES_ADD'
